# Site settings
title: SeedProd

# Build settings
paginate: 5
paginate_path: "blog/page:num/"
markdown: kramdown
permalink: /:title
exclude: ["_less","config.codekit","style.less","README","Rakefile",".DS_Store"]

# Gems
gems:
  - jekyll-sitemap
