# Site settings
title: SeedProd
url: https://www.seedprod.com

# Build settings
paginate: 10
paginate_path: "blog/page/:num/"
markdown: kramdown
permalink: /:title
exclude: ["_less","config.codekit","style.less","README","Rakefile",".DS_Store","deploy.sh"]
include: [".htaccess"]

# Gems
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
